name: Deploy Terraform infrastructure - Shared
on: 
  push:
    branches:
      - main
    paths:
      - deploy/**
      - .github/workflows/deploy-infrastructure-shd.yaml
    

permissions:
      id-token: write
      contents: read
      
jobs: 
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_azure_cicd_sp_name: ${{ vars.AZURE_GITHUB_SPNAME }}
      TF_VAR_shared_subscription_id: ${{ vars.SHARED_SUBSCRIPTION_ID }}
    steps:
    - name: Checkout    
      uses: actions/checkout@v3   
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Apply
      run: terraform apply
      